package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * AuditLog generated by hbm2java
 */
@Entity
@Table(name = "audit_log", schema = "public")
public class AuditLog implements java.io.Serializable {

	private int id;
	private Date timestamp;
	private String userId;
	private String ipAddress;
	private boolean success;
	private String event;

	public AuditLog() {
	}

	public AuditLog(int id, String ipAddress, boolean success, String event) {
		this.id = id;
		this.ipAddress = ipAddress;
		this.success = success;
		this.event = event;
	}

	public AuditLog(int id, String userId, String ipAddress, boolean success, String event) {
		this.id = id;
		this.userId = userId;
		this.ipAddress = ipAddress;
		this.success = success;
		this.event = event;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestamp", nullable = false, length = 29)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "user_id", length = 254)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "ip_address", nullable = false)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Column(name = "success", nullable = false)
	public boolean isSuccess() {
		return this.success;
	}

	public void setSuccess(boolean success) {
		this.success = success;
	}

	@Column(name = "event", nullable = false)
	public String getEvent() {
		return this.event;
	}

	public void setEvent(String event) {
		this.event = event;
	}

}
