package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * IdMarkType generated by hbm2java
 */
@Entity
@Table(name = "id_mark_type", schema = "public")
public class IdMarkType implements java.io.Serializable {

	private int id;
	private String typeName;

	public IdMarkType() {
	}

	public IdMarkType(int id) {
		this.id = id;
	}

	public IdMarkType(int id, String typeName) {
		this.id = id;
		this.typeName = typeName;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "type_name", length = 20)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

}
