package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * IdMarkLocation generated by hbm2java
 */
@Entity
@Table(name = "id_mark_location", schema = "public")
public class IdMarkLocation implements java.io.Serializable {

	private int id;
	private String idLocation;

	public IdMarkLocation() {
	}

	public IdMarkLocation(int id) {
		this.id = id;
	}

	public IdMarkLocation(int id, String idLocation) {
		this.id = id;
		this.idLocation = idLocation;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "id_location", length = 30)
	public String getIdLocation() {
		return this.idLocation;
	}

	public void setIdLocation(String idLocation) {
		this.idLocation = idLocation;
	}

}
