package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Media generated by hbm2java
 */
@Entity
@Table(name = "media", schema = "public")
public class Media implements java.io.Serializable {

	private int id;
	private RefInternetMediaSubType refInternetMediaSubType;
	private RefInternetMediaType refInternetMediaType;
	private NoteMedia noteMedia;
	private ProfileMedia profileMedia;

	public Media() {
	}

	public Media(int id, RefInternetMediaSubType refInternetMediaSubType, RefInternetMediaType refInternetMediaType) {
		this.id = id;
		this.refInternetMediaSubType = refInternetMediaSubType;
		this.refInternetMediaType = refInternetMediaType;
	}

	public Media(int id, RefInternetMediaSubType refInternetMediaSubType, RefInternetMediaType refInternetMediaType,
			NoteMedia noteMedia, ProfileMedia profileMedia) {
		this.id = id;
		this.refInternetMediaSubType = refInternetMediaSubType;
		this.refInternetMediaType = refInternetMediaType;
		this.noteMedia = noteMedia;
		this.profileMedia = profileMedia;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sub_type_id", nullable = false)
	public RefInternetMediaSubType getRefInternetMediaSubType() {
		return this.refInternetMediaSubType;
	}

	public void setRefInternetMediaSubType(RefInternetMediaSubType refInternetMediaSubType) {
		this.refInternetMediaSubType = refInternetMediaSubType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_id", nullable = false)
	public RefInternetMediaType getRefInternetMediaType() {
		return this.refInternetMediaType;
	}

	public void setRefInternetMediaType(RefInternetMediaType refInternetMediaType) {
		this.refInternetMediaType = refInternetMediaType;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "media")
	public NoteMedia getNoteMedia() {
		return this.noteMedia;
	}

	public void setNoteMedia(NoteMedia noteMedia) {
		this.noteMedia = noteMedia;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "media")
	public ProfileMedia getProfileMedia() {
		return this.profileMedia;
	}

	public void setProfileMedia(ProfileMedia profileMedia) {
		this.profileMedia = profileMedia;
	}

}
