package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ModeratorLock generated by hbm2java
 */
@Entity
@Table(name = "moderator_lock", schema = "public")
public class ModeratorLock implements java.io.Serializable {

	private int moderatorId;
	private Integer childId;
	private Date lockTime;

	public ModeratorLock() {
	}

	public ModeratorLock(int moderatorId) {
		this.moderatorId = moderatorId;
	}

	public ModeratorLock(int moderatorId, Integer childId, Date lockTime) {
		this.moderatorId = moderatorId;
		this.childId = childId;
		this.lockTime = lockTime;
	}

	@Id

	@Column(name = "moderator_id", unique = true, nullable = false)
	public int getModeratorId() {
		return this.moderatorId;
	}

	public void setModeratorId(int moderatorId) {
		this.moderatorId = moderatorId;
	}

	@Column(name = "child_id")
	public Integer getChildId() {
		return this.childId;
	}

	public void setChildId(Integer childId) {
		this.childId = childId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lock_time", length = 29)
	public Date getLockTime() {
		return this.lockTime;
	}

	public void setLockTime(Date lockTime) {
		this.lockTime = lockTime;
	}

}
