package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * PoliceStationList generated by hbm2java
 */
@Entity
@Table(name = "police_station_list", schema = "public")
@JsonIdentityInfo(
		  generator = ObjectIdGenerators.PropertyGenerator.class, 
		  property = "id")
public class PoliceStationList implements java.io.Serializable {

	private int id;
	private RefDistrict refDistrict;
	private RefState refState;
	private String cipaStateCode;
	private String stateName;
	private String cipaDistrictCode;
	private String districtName;
	private String policeStationCode;
	private String policeStationName;

	public PoliceStationList() {
	}

	public PoliceStationList(int id) {
		this.id = id;
	}

	public PoliceStationList(int id, RefDistrict refDistrict, RefState refState, String cipaStateCode, String stateName,
			String cipaDistrictCode, String districtName, String policeStationCode, String policeStationName) {
		this.id = id;
		this.refDistrict = refDistrict;
		this.refState = refState;
		this.cipaStateCode = cipaStateCode;
		this.stateName = stateName;
		this.cipaDistrictCode = cipaDistrictCode;
		this.districtName = districtName;
		this.policeStationCode = policeStationCode;
		this.policeStationName = policeStationName;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "district_code", columnDefinition="bpchar(3)")
	public RefDistrict getRefDistrict() {
		return this.refDistrict;
	}

	public void setRefDistrict(RefDistrict refDistrict) {
		this.refDistrict = refDistrict;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "state_code", columnDefinition="bpchar(2)")
	public RefState getRefState() {
		return this.refState;
	}

	public void setRefState(RefState refState) {
		this.refState = refState;
	}

	@Column(name = "cipa_state_code", columnDefinition="bpchar(2)", length = 2)
	public String getCipaStateCode() {
		return this.cipaStateCode;
	}

	public void setCipaStateCode(String cipaStateCode) {
		this.cipaStateCode = cipaStateCode;
	}

	@Column(name = "state_name", length = 30)
	public String getStateName() {
		return this.stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	@Column(name = "cipa_district_code", columnDefinition="bpchar(3)", length = 3)
	public String getCipaDistrictCode() {
		return this.cipaDistrictCode;
	}

	public void setCipaDistrictCode(String cipaDistrictCode) {
		this.cipaDistrictCode = cipaDistrictCode;
	}

	@Column(name = "district_name", length = 50)
	public String getDistrictName() {
		return this.districtName;
	}

	public void setDistrictName(String districtName) {
		this.districtName = districtName;
	}

	@Column(name = "police_station_code", length = 3)
	public String getPoliceStationCode() {
		return this.policeStationCode;
	}

	public void setPoliceStationCode(String policeStationCode) {
		this.policeStationCode = policeStationCode;
	}

	@Column(name = "police_station_name", length = 50)
	public String getPoliceStationName() {
		return this.policeStationName;
	}

	public void setPoliceStationName(String policeStationName) {
		this.policeStationName = policeStationName;
	}

}
