package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ProfileMedia generated by hbm2java
 */
@Entity
@Table(name = "profile_media", schema = "public")
public class ProfileMedia implements java.io.Serializable {

	private int mediaId;
	private Media media;
	private Profile profile;

	public ProfileMedia() {
	}

	public ProfileMedia(Media media, Profile profile) {
		this.media = media;
		this.profile = profile;
	}

	@GenericGenerator(name = "com.aks.app.model.all.entity.ProfileMediaIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "media"))
	@Id
	@GeneratedValue(generator = "com.aks.app.model.all.entity.ProfileMediaIdGenerator")

	@Column(name = "media_id", unique = true, nullable = false)
	public int getMediaId() {
		return this.mediaId;
	}

	public void setMediaId(int mediaId) {
		this.mediaId = mediaId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Media getMedia() {
		return this.media;
	}

	public void setMedia(Media media) {
		this.media = media;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "profile_id", nullable = false)
	public Profile getProfile() {
		return this.profile;
	}

	public void setProfile(Profile profile) {
		this.profile = profile;
	}

}
