package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProfileModeration generated by hbm2java
 */
@Entity
@Table(name = "profile_moderation", schema = "public")
public class ProfileModeration implements java.io.Serializable {

	private int id;
	private Profile profile;
	private UserLoginDetails userLoginDetails;
	private String comment;
	private Date entryDate;
	private int moderatorStatus;

	public ProfileModeration() {
	}

	public ProfileModeration(int id, Profile profile, UserLoginDetails userLoginDetails, String comment, Date entryDate,
			int moderatorStatus) {
		this.id = id;
		this.profile = profile;
		this.userLoginDetails = userLoginDetails;
		this.comment = comment;
		this.entryDate = entryDate;
		this.moderatorStatus = moderatorStatus;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "profile_id", nullable = false)
	public Profile getProfile() {
		return this.profile;
	}

	public void setProfile(Profile profile) {
		this.profile = profile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "moderator_id", nullable = false)
	public UserLoginDetails getUserLoginDetails() {
		return this.userLoginDetails;
	}

	public void setUserLoginDetails(UserLoginDetails userLoginDetails) {
		this.userLoginDetails = userLoginDetails;
	}

	@Column(name = "comment", nullable = false, length = 1000)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "entry_date", nullable = false, length = 29)
	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	@Column(name = "moderator_status", nullable = false)
	public int getModeratorStatus() {
		return this.moderatorStatus;
	}

	public void setModeratorStatus(int moderatorStatus) {
		this.moderatorStatus = moderatorStatus;
	}

}
