package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name = "profile", schema = "public")
public class Profile implements java.io.Serializable {

	private int id;
	private RefComplexion refComplexion;
	private RefDistrict refDistrict;
	private RefGender refGender;
	private RefModerationStatus refModerationStatus;
	private RefNcrbDistrict refNcrbDistrict;
	private RefNcrbPoliceStation refNcrbPoliceStation;
	private RefNcrbState refNcrbState;
	private RefState refState;
	private RegisteredUser registeredUser;
	private String name;
	private Date dateOfBirth;
	private Integer ageYears;
	private Integer hairColorId;
	private Integer eyeColorId;
	private Integer heightFeet;
	private Integer buildId;
	private String address;
	private String pinCode;
	private String identificationMarks;
	private String description;
	private char missingOrSighting;
	private Date entryDate;
	private Date expiryDate;
	private Character relationship;
	private Integer hairSizeId;
	private Integer eyesTypeId;
	private Integer spectaclesTypeId;
	private Integer spectaclesColorId;
	private Integer noseTypeId;
	private Integer earsSizeId;
	private Integer earsTypeId;
	private Integer frontTeethId;
	private Integer lipsColorId;
	private Integer lipsTypeId;
	private Integer neckTypeId;
	private Integer skinTypeId;
	private Boolean physicalDisability;
	private Boolean mentalDisability;
	private Integer topWearId;
	private Integer topWearColorId;
	private Integer bottomWearId;
	private Integer bottomWearColorId;
	private Integer footwearId;
	private Integer footwearColorId;
	private String fatherName;
	private String fatherNumber;
	private String motherName;
	private String motherNumber;
	private String homeAddress;
	private Date lastTimeSeenPlace;
	private Integer primaryLanguageId;
	private Integer otherKnownLanguagesId;
	private String schoolName;
	private String schoolAddress;
	private Character status;
	private String fatherEmail;
	private String motherEmail;
	private Integer ageMonths;
	private Integer heightInches;
	private String latitude;
	private String longitude;
	private Date eventDate;
	private String reason;
	private Boolean contactAuthor;
	private String disabilityDetails;
	private String aadhaarNumber;
	private String dataSource;
	private String firNumber;
	private Date firDate;
	private Integer speechId;
	private Set<ProfileModeration> profileModerations = new HashSet<ProfileModeration>(0);
	private Set<ProfileMedia> profileMedias = new HashSet<ProfileMedia>(0);
	private Set<ProfileClosureReasonDetails> profileClosureReasonDetailses = new HashSet<ProfileClosureReasonDetails>(
			0);
	private Set<ProfileTextualDetail> profileTextualDetails = new HashSet<ProfileTextualDetail>(0);

	public Profile() {
	}

	public Profile(int id, RefModerationStatus refModerationStatus, RegisteredUser registeredUser,
			char missingOrSighting, Date entryDate, String dataSource) {
		this.id = id;
		this.refModerationStatus = refModerationStatus;
		this.registeredUser = registeredUser;
		this.missingOrSighting = missingOrSighting;
		this.entryDate = entryDate;
		this.dataSource = dataSource;
	}

	public Profile(int id, RefComplexion refComplexion, RefDistrict refDistrict, RefGender refGender,
			RefModerationStatus refModerationStatus, RefNcrbDistrict refNcrbDistrict,
			RefNcrbPoliceStation refNcrbPoliceStation, RefNcrbState refNcrbState, RefState refState,
			RegisteredUser registeredUser, String name, Date dateOfBirth, Integer ageYears, Integer hairColorId,
			Integer eyeColorId, Integer heightFeet, Integer buildId, String address, String pinCode,
			String identificationMarks, String description, char missingOrSighting, Date entryDate, Date expiryDate,
			Character relationship, Integer hairSizeId, Integer eyesTypeId, Integer spectaclesTypeId,
			Integer spectaclesColorId, Integer noseTypeId, Integer earsSizeId, Integer earsTypeId, Integer frontTeethId,
			Integer lipsColorId, Integer lipsTypeId, Integer neckTypeId, Integer skinTypeId, Boolean physicalDisability,
			Boolean mentalDisability, Integer topWearId, Integer topWearColorId, Integer bottomWearId,
			Integer bottomWearColorId, Integer footwearId, Integer footwearColorId, String fatherName,
			String fatherNumber, String motherName, String motherNumber, String homeAddress, Date lastTimeSeenPlace,
			Integer primaryLanguageId, Integer otherKnownLanguagesId, String schoolName, String schoolAddress,
			Character status, String fatherEmail, String motherEmail, Integer ageMonths, Integer heightInches,
			String latitude, String longitude, Date eventDate, String reason, Boolean contactAuthor,
			String disabilityDetails, String aadhaarNumber, String dataSource, String firNumber, Date firDate,
			Integer speechId, Set<ProfileModeration> profileModerations, Set<ProfileMedia> profileMedias,
			Set<ProfileClosureReasonDetails> profileClosureReasonDetailses,
			Set<ProfileTextualDetail> profileTextualDetails) {
		this.id = id;
		this.refComplexion = refComplexion;
		this.refDistrict = refDistrict;
		this.refGender = refGender;
		this.refModerationStatus = refModerationStatus;
		this.refNcrbDistrict = refNcrbDistrict;
		this.refNcrbPoliceStation = refNcrbPoliceStation;
		this.refNcrbState = refNcrbState;
		this.refState = refState;
		this.registeredUser = registeredUser;
		this.name = name;
		this.dateOfBirth = dateOfBirth;
		this.ageYears = ageYears;
		this.hairColorId = hairColorId;
		this.eyeColorId = eyeColorId;
		this.heightFeet = heightFeet;
		this.buildId = buildId;
		this.address = address;
		this.pinCode = pinCode;
		this.identificationMarks = identificationMarks;
		this.description = description;
		this.missingOrSighting = missingOrSighting;
		this.entryDate = entryDate;
		this.expiryDate = expiryDate;
		this.relationship = relationship;
		this.hairSizeId = hairSizeId;
		this.eyesTypeId = eyesTypeId;
		this.spectaclesTypeId = spectaclesTypeId;
		this.spectaclesColorId = spectaclesColorId;
		this.noseTypeId = noseTypeId;
		this.earsSizeId = earsSizeId;
		this.earsTypeId = earsTypeId;
		this.frontTeethId = frontTeethId;
		this.lipsColorId = lipsColorId;
		this.lipsTypeId = lipsTypeId;
		this.neckTypeId = neckTypeId;
		this.skinTypeId = skinTypeId;
		this.physicalDisability = physicalDisability;
		this.mentalDisability = mentalDisability;
		this.topWearId = topWearId;
		this.topWearColorId = topWearColorId;
		this.bottomWearId = bottomWearId;
		this.bottomWearColorId = bottomWearColorId;
		this.footwearId = footwearId;
		this.footwearColorId = footwearColorId;
		this.fatherName = fatherName;
		this.fatherNumber = fatherNumber;
		this.motherName = motherName;
		this.motherNumber = motherNumber;
		this.homeAddress = homeAddress;
		this.lastTimeSeenPlace = lastTimeSeenPlace;
		this.primaryLanguageId = primaryLanguageId;
		this.otherKnownLanguagesId = otherKnownLanguagesId;
		this.schoolName = schoolName;
		this.schoolAddress = schoolAddress;
		this.status = status;
		this.fatherEmail = fatherEmail;
		this.motherEmail = motherEmail;
		this.ageMonths = ageMonths;
		this.heightInches = heightInches;
		this.latitude = latitude;
		this.longitude = longitude;
		this.eventDate = eventDate;
		this.reason = reason;
		this.contactAuthor = contactAuthor;
		this.disabilityDetails = disabilityDetails;
		this.aadhaarNumber = aadhaarNumber;
		this.dataSource = dataSource;
		this.firNumber = firNumber;
		this.firDate = firDate;
		this.speechId = speechId;
		this.profileModerations = profileModerations;
		this.profileMedias = profileMedias;
		this.profileClosureReasonDetailses = profileClosureReasonDetailses;
		this.profileTextualDetails = profileTextualDetails;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "complexion_id")
	public RefComplexion getRefComplexion() {
		return this.refComplexion;
	}

	public void setRefComplexion(RefComplexion refComplexion) {
		this.refComplexion = refComplexion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "district_id", columnDefinition="bpchar(3)")
	public RefDistrict getRefDistrict() {
		return this.refDistrict;
	}

	public void setRefDistrict(RefDistrict refDistrict) {
		this.refDistrict = refDistrict;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gender_id")
	public RefGender getRefGender() {
		return this.refGender;
	}

	public void setRefGender(RefGender refGender) {
		this.refGender = refGender;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "moderation_status", nullable = false)
	public RefModerationStatus getRefModerationStatus() {
		return this.refModerationStatus;
	}

	public void setRefModerationStatus(RefModerationStatus refModerationStatus) {
		this.refModerationStatus = refModerationStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fir_district_id")
	public RefNcrbDistrict getRefNcrbDistrict() {
		return this.refNcrbDistrict;
	}

	public void setRefNcrbDistrict(RefNcrbDistrict refNcrbDistrict) {
		this.refNcrbDistrict = refNcrbDistrict;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fir_police_station_code")
	public RefNcrbPoliceStation getRefNcrbPoliceStation() {
		return this.refNcrbPoliceStation;
	}

	public void setRefNcrbPoliceStation(RefNcrbPoliceStation refNcrbPoliceStation) {
		this.refNcrbPoliceStation = refNcrbPoliceStation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fir_state_id")
	public RefNcrbState getRefNcrbState() {
		return this.refNcrbState;
	}

	public void setRefNcrbState(RefNcrbState refNcrbState) {
		this.refNcrbState = refNcrbState;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "state_id", columnDefinition="bpchar(2)")
	public RefState getRefState() {
		return this.refState;
	}

	public void setRefState(RefState refState) {
		this.refState = refState;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "author_id", nullable = false)
	public RegisteredUser getRegisteredUser() {
		return this.registeredUser;
	}

	public void setRegisteredUser(RegisteredUser registeredUser) {
		this.registeredUser = registeredUser;
	}

	@Column(name = "name", length = 99)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_of_birth", length = 13)
	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Column(name = "age_years")
	public Integer getAgeYears() {
		return this.ageYears;
	}

	public void setAgeYears(Integer ageYears) {
		this.ageYears = ageYears;
	}

	@Column(name = "hair_color_id")
	public Integer getHairColorId() {
		return this.hairColorId;
	}

	public void setHairColorId(Integer hairColorId) {
		this.hairColorId = hairColorId;
	}

	@Column(name = "eye_color_id")
	public Integer getEyeColorId() {
		return this.eyeColorId;
	}

	public void setEyeColorId(Integer eyeColorId) {
		this.eyeColorId = eyeColorId;
	}

	@Column(name = "height_feet")
	public Integer getHeightFeet() {
		return this.heightFeet;
	}

	public void setHeightFeet(Integer heightFeet) {
		this.heightFeet = heightFeet;
	}

	@Column(name = "build_id")
	public Integer getBuildId() {
		return this.buildId;
	}

	public void setBuildId(Integer buildId) {
		this.buildId = buildId;
	}

	@Column(name = "address", length = 150)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "pin_code", length = 6)
	public String getPinCode() {
		return this.pinCode;
	}

	public void setPinCode(String pinCode) {
		this.pinCode = pinCode;
	}

	@Column(name = "identification_marks", length = 100)
	public String getIdentificationMarks() {
		return this.identificationMarks;
	}

	public void setIdentificationMarks(String identificationMarks) {
		this.identificationMarks = identificationMarks;
	}

	@Column(name = "description", length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "missing_or_sighting", nullable = false, length = 1)
	public char getMissingOrSighting() {
		return this.missingOrSighting;
	}

	public void setMissingOrSighting(char missingOrSighting) {
		this.missingOrSighting = missingOrSighting;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "entry_date", nullable = false, length = 29)
	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expiry_date", length = 29)
	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	@Column(name = "relationship", length = 1)
	public Character getRelationship() {
		return this.relationship;
	}

	public void setRelationship(Character relationship) {
		this.relationship = relationship;
	}

	@Column(name = "hair_size_id")
	public Integer getHairSizeId() {
		return this.hairSizeId;
	}

	public void setHairSizeId(Integer hairSizeId) {
		this.hairSizeId = hairSizeId;
	}

	@Column(name = "eyes_type_id")
	public Integer getEyesTypeId() {
		return this.eyesTypeId;
	}

	public void setEyesTypeId(Integer eyesTypeId) {
		this.eyesTypeId = eyesTypeId;
	}

	@Column(name = "spectacles_type_id")
	public Integer getSpectaclesTypeId() {
		return this.spectaclesTypeId;
	}

	public void setSpectaclesTypeId(Integer spectaclesTypeId) {
		this.spectaclesTypeId = spectaclesTypeId;
	}

	@Column(name = "spectacles_color_id")
	public Integer getSpectaclesColorId() {
		return this.spectaclesColorId;
	}

	public void setSpectaclesColorId(Integer spectaclesColorId) {
		this.spectaclesColorId = spectaclesColorId;
	}

	@Column(name = "nose_type_id")
	public Integer getNoseTypeId() {
		return this.noseTypeId;
	}

	public void setNoseTypeId(Integer noseTypeId) {
		this.noseTypeId = noseTypeId;
	}

	@Column(name = "ears_size_id")
	public Integer getEarsSizeId() {
		return this.earsSizeId;
	}

	public void setEarsSizeId(Integer earsSizeId) {
		this.earsSizeId = earsSizeId;
	}

	@Column(name = "ears_type_id")
	public Integer getEarsTypeId() {
		return this.earsTypeId;
	}

	public void setEarsTypeId(Integer earsTypeId) {
		this.earsTypeId = earsTypeId;
	}

	@Column(name = "front_teeth_id")
	public Integer getFrontTeethId() {
		return this.frontTeethId;
	}

	public void setFrontTeethId(Integer frontTeethId) {
		this.frontTeethId = frontTeethId;
	}

	@Column(name = "lips_color_id")
	public Integer getLipsColorId() {
		return this.lipsColorId;
	}

	public void setLipsColorId(Integer lipsColorId) {
		this.lipsColorId = lipsColorId;
	}

	@Column(name = "lips_type_id")
	public Integer getLipsTypeId() {
		return this.lipsTypeId;
	}

	public void setLipsTypeId(Integer lipsTypeId) {
		this.lipsTypeId = lipsTypeId;
	}

	@Column(name = "neck_type_id")
	public Integer getNeckTypeId() {
		return this.neckTypeId;
	}

	public void setNeckTypeId(Integer neckTypeId) {
		this.neckTypeId = neckTypeId;
	}

	@Column(name = "skin_type_id")
	public Integer getSkinTypeId() {
		return this.skinTypeId;
	}

	public void setSkinTypeId(Integer skinTypeId) {
		this.skinTypeId = skinTypeId;
	}

	@Column(name = "physical_disability")
	public Boolean getPhysicalDisability() {
		return this.physicalDisability;
	}

	public void setPhysicalDisability(Boolean physicalDisability) {
		this.physicalDisability = physicalDisability;
	}

	@Column(name = "mental_disability")
	public Boolean getMentalDisability() {
		return this.mentalDisability;
	}

	public void setMentalDisability(Boolean mentalDisability) {
		this.mentalDisability = mentalDisability;
	}

	@Column(name = "top_wear_id")
	public Integer getTopWearId() {
		return this.topWearId;
	}

	public void setTopWearId(Integer topWearId) {
		this.topWearId = topWearId;
	}

	@Column(name = "top_wear_color_id")
	public Integer getTopWearColorId() {
		return this.topWearColorId;
	}

	public void setTopWearColorId(Integer topWearColorId) {
		this.topWearColorId = topWearColorId;
	}

	@Column(name = "bottom_wear_id")
	public Integer getBottomWearId() {
		return this.bottomWearId;
	}

	public void setBottomWearId(Integer bottomWearId) {
		this.bottomWearId = bottomWearId;
	}

	@Column(name = "bottom_wear_color_id")
	public Integer getBottomWearColorId() {
		return this.bottomWearColorId;
	}

	public void setBottomWearColorId(Integer bottomWearColorId) {
		this.bottomWearColorId = bottomWearColorId;
	}

	@Column(name = "footwear_id")
	public Integer getFootwearId() {
		return this.footwearId;
	}

	public void setFootwearId(Integer footwearId) {
		this.footwearId = footwearId;
	}

	@Column(name = "footwear_color_id")
	public Integer getFootwearColorId() {
		return this.footwearColorId;
	}

	public void setFootwearColorId(Integer footwearColorId) {
		this.footwearColorId = footwearColorId;
	}

	@Column(name = "father_name", length = 50)
	public String getFatherName() {
		return this.fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}

	@Column(name = "father_number", columnDefinition="bpchar(10)", length = 15)
	public String getFatherNumber() {
		return this.fatherNumber;
	}

	public void setFatherNumber(String fatherNumber) {
		this.fatherNumber = fatherNumber;
	}

	@Column(name = "mother_name", length = 50)
	public String getMotherName() {
		return this.motherName;
	}

	public void setMotherName(String motherName) {
		this.motherName = motherName;
	}

	@Column(name = "mother_number", length = 15)
	public String getMotherNumber() {
		return this.motherNumber;
	}

	public void setMotherNumber(String motherNumber) {
		this.motherNumber = motherNumber;
	}

	@Column(name = "home_address", length = 250)
	public String getHomeAddress() {
		return this.homeAddress;
	}

	public void setHomeAddress(String homeAddress) {
		this.homeAddress = homeAddress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_time_seen_place", length = 29)
	public Date getLastTimeSeenPlace() {
		return this.lastTimeSeenPlace;
	}

	public void setLastTimeSeenPlace(Date lastTimeSeenPlace) {
		this.lastTimeSeenPlace = lastTimeSeenPlace;
	}

	@Column(name = "primary_language_id")
	public Integer getPrimaryLanguageId() {
		return this.primaryLanguageId;
	}

	public void setPrimaryLanguageId(Integer primaryLanguageId) {
		this.primaryLanguageId = primaryLanguageId;
	}

	@Column(name = "other_known_languages_id")
	public Integer getOtherKnownLanguagesId() {
		return this.otherKnownLanguagesId;
	}

	public void setOtherKnownLanguagesId(Integer otherKnownLanguagesId) {
		this.otherKnownLanguagesId = otherKnownLanguagesId;
	}

	@Column(name = "school_name", length = 250)
	public String getSchoolName() {
		return this.schoolName;
	}

	public void setSchoolName(String schoolName) {
		this.schoolName = schoolName;
	}

	@Column(name = "school_address", length = 250)
	public String getSchoolAddress() {
		return this.schoolAddress;
	}

	public void setSchoolAddress(String schoolAddress) {
		this.schoolAddress = schoolAddress;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "father_email", length = 254)
	public String getFatherEmail() {
		return this.fatherEmail;
	}

	public void setFatherEmail(String fatherEmail) {
		this.fatherEmail = fatherEmail;
	}

	@Column(name = "mother_email", length = 254)
	public String getMotherEmail() {
		return this.motherEmail;
	}

	public void setMotherEmail(String motherEmail) {
		this.motherEmail = motherEmail;
	}

	@Column(name = "age_months")
	public Integer getAgeMonths() {
		return this.ageMonths;
	}

	public void setAgeMonths(Integer ageMonths) {
		this.ageMonths = ageMonths;
	}

	@Column(name = "height_inches")
	public Integer getHeightInches() {
		return this.heightInches;
	}

	public void setHeightInches(Integer heightInches) {
		this.heightInches = heightInches;
	}

	@Column(name = "latitude")
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude")
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "event_date", length = 13)
	public Date getEventDate() {
		return this.eventDate;
	}

	public void setEventDate(Date eventDate) {
		this.eventDate = eventDate;
	}

	@Column(name = "reason", length = 1000)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "contact_author")
	public Boolean getContactAuthor() {
		return this.contactAuthor;
	}

	public void setContactAuthor(Boolean contactAuthor) {
		this.contactAuthor = contactAuthor;
	}

	@Column(name = "disability_details", length = 250)
	public String getDisabilityDetails() {
		return this.disabilityDetails;
	}

	public void setDisabilityDetails(String disabilityDetails) {
		this.disabilityDetails = disabilityDetails;
	}

	@Column(name = "aadhaar_number", length = 12)
	public String getAadhaarNumber() {
		return this.aadhaarNumber;
	}

	public void setAadhaarNumber(String aadhaarNumber) {
		this.aadhaarNumber = aadhaarNumber;
	}

	@Column(name = "data_source", nullable = false, length = 10)
	public String getDataSource() {
		return this.dataSource;
	}

	public void setDataSource(String dataSource) {
		this.dataSource = dataSource;
	}

	@Column(name = "fir_number", length = 20)
	public String getFirNumber() {
		return this.firNumber;
	}

	public void setFirNumber(String firNumber) {
		this.firNumber = firNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fir_date", length = 13)
	public Date getFirDate() {
		return this.firDate;
	}

	public void setFirDate(Date firDate) {
		this.firDate = firDate;
	}

	@Column(name = "speech_id")
	public Integer getSpeechId() {
		return this.speechId;
	}

	public void setSpeechId(Integer speechId) {
		this.speechId = speechId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profile")
	public Set<ProfileModeration> getProfileModerations() {
		return this.profileModerations;
	}

	public void setProfileModerations(Set<ProfileModeration> profileModerations) {
		this.profileModerations = profileModerations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profile")
	public Set<ProfileMedia> getProfileMedias() {
		return this.profileMedias;
	}

	public void setProfileMedias(Set<ProfileMedia> profileMedias) {
		this.profileMedias = profileMedias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profile")
	public Set<ProfileClosureReasonDetails> getProfileClosureReasonDetailses() {
		return this.profileClosureReasonDetailses;
	}

	public void setProfileClosureReasonDetailses(Set<ProfileClosureReasonDetails> profileClosureReasonDetailses) {
		this.profileClosureReasonDetailses = profileClosureReasonDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profile")
	public Set<ProfileTextualDetail> getProfileTextualDetails() {
		return this.profileTextualDetails;
	}

	public void setProfileTextualDetails(Set<ProfileTextualDetail> profileTextualDetails) {
		this.profileTextualDetails = profileTextualDetails;
	}

}
