package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProfileClosureReasonDetails generated by hbm2java
 */
@Entity
@Table(name = "profile_closure_reason_details", schema = "public")
public class ProfileClosureReasonDetails implements java.io.Serializable {

	private int id;
	private Profile profile;
	private RegisteredUser registeredUser;
	private Date entryDate;
	private Boolean childFound;
	private String reason;

	public ProfileClosureReasonDetails() {
	}

	public ProfileClosureReasonDetails(int id, Profile profile, RegisteredUser registeredUser, Date entryDate) {
		this.id = id;
		this.profile = profile;
		this.registeredUser = registeredUser;
		this.entryDate = entryDate;
	}

	public ProfileClosureReasonDetails(int id, Profile profile, RegisteredUser registeredUser, Date entryDate,
			Boolean childFound, String reason) {
		this.id = id;
		this.profile = profile;
		this.registeredUser = registeredUser;
		this.entryDate = entryDate;
		this.childFound = childFound;
		this.reason = reason;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "profile_id", nullable = false)
	public Profile getProfile() {
		return this.profile;
	}

	public void setProfile(Profile profile) {
		this.profile = profile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public RegisteredUser getRegisteredUser() {
		return this.registeredUser;
	}

	public void setRegisteredUser(RegisteredUser registeredUser) {
		this.registeredUser = registeredUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "entry_date", nullable = false, length = 29)
	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	@Column(name = "child_found")
	public Boolean getChildFound() {
		return this.childFound;
	}

	public void setChildFound(Boolean childFound) {
		this.childFound = childFound;
	}

	@Column(name = "reason", length = 245)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

}
