package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RefAgeMonths generated by hbm2java
 */
@Entity
@Table(name = "ref_age_months", schema = "public")
public class RefAgeMonths implements java.io.Serializable {

	private int id;
	private Integer months;

	public RefAgeMonths() {
	}

	public RefAgeMonths(int id) {
		this.id = id;
	}

	public RefAgeMonths(int id, Integer months) {
		this.id = id;
		this.months = months;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "months")
	public Integer getMonths() {
		return this.months;
	}

	public void setMonths(Integer months) {
		this.months = months;
	}

}
