package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RefAgeYrs generated by hbm2java
 */
@Entity
@Table(name = "ref_age_yrs", schema = "public")
public class RefAgeYrs implements java.io.Serializable {

	private int id;
	private Integer years;

	public RefAgeYrs() {
	}

	public RefAgeYrs(int id) {
		this.id = id;
	}

	public RefAgeYrs(int id, Integer years) {
		this.id = id;
		this.years = years;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "years")
	public Integer getYears() {
		return this.years;
	}

	public void setYears(Integer years) {
		this.years = years;
	}

}
