package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RefAuditEvent generated by hbm2java
 */
@Entity
@Table(name = "ref_audit_event", schema = "public")
public class RefAuditEvent implements java.io.Serializable {

	private int id;
	private String event;

	public RefAuditEvent() {
	}

	public RefAuditEvent(int id, String event) {
		this.id = id;
		this.event = event;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "event", nullable = false)
	public String getEvent() {
		return this.event;
	}

	public void setEvent(String event) {
		this.event = event;
	}

}
