package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * RefBuild generated by hbm2java
 */
@Entity
@Table(name = "ref_build", schema = "public")
@JsonIdentityInfo(
		  generator = ObjectIdGenerators.PropertyGenerator.class, 
		  property = "id")
public class RefBuild implements java.io.Serializable {

	private int id;
	private String name;
	private Set<RefBuildTranslation> refBuildTranslations = new HashSet<RefBuildTranslation>(0);

	public RefBuild() {
	}

	public RefBuild(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public RefBuild(int id, String name, Set<RefBuildTranslation> refBuildTranslations) {
		this.id = id;
		this.name = name;
		this.refBuildTranslations = refBuildTranslations;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 254)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refBuild")
	public Set<RefBuildTranslation> getRefBuildTranslations() {
		return this.refBuildTranslations;
	}

	public void setRefBuildTranslations(Set<RefBuildTranslation> refBuildTranslations) {
		this.refBuildTranslations = refBuildTranslations;
	}

}
