package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RefBottomWearTranslation generated by hbm2java
 */
@Entity
@Table(name = "ref_bottom_wear_translation", schema = "public")
public class RefBottomWearTranslation implements java.io.Serializable {

	private int id;
	private RefLanguage refLanguage;
	private int bottomWearId;
	private String name;

	public RefBottomWearTranslation() {
	}

	public RefBottomWearTranslation(int id, RefLanguage refLanguage, int bottomWearId) {
		this.id = id;
		this.refLanguage = refLanguage;
		this.bottomWearId = bottomWearId;
	}

	public RefBottomWearTranslation(int id, RefLanguage refLanguage, int bottomWearId, String name) {
		this.id = id;
		this.refLanguage = refLanguage;
		this.bottomWearId = bottomWearId;
		this.name = name;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language_id", columnDefinition="bpchar(3)", nullable = false)
	public RefLanguage getRefLanguage() {
		return this.refLanguage;
	}

	public void setRefLanguage(RefLanguage refLanguage) {
		this.refLanguage = refLanguage;
	}

	@Column(name = "bottom_wear_id", nullable = false)
	public int getBottomWearId() {
		return this.bottomWearId;
	}

	public void setBottomWearId(int bottomWearId) {
		this.bottomWearId = bottomWearId;
	}

	@Column(name = "name", length = 254)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
