package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RefBottomWearColor generated by hbm2java
 */
@Entity
@Table(name = "ref_bottom_wear_color", schema = "public")
public class RefBottomWearColor implements java.io.Serializable {

	private int id;
	private String bottomWearColor;

	public RefBottomWearColor() {
	}

	public RefBottomWearColor(int id) {
		this.id = id;
	}

	public RefBottomWearColor(int id, String bottomWearColor) {
		this.id = id;
		this.bottomWearColor = bottomWearColor;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "bottom_wear_color", length = 15)
	public String getBottomWearColor() {
		return this.bottomWearColor;
	}

	public void setBottomWearColor(String bottomWearColor) {
		this.bottomWearColor = bottomWearColor;
	}

}
