package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RefBottomWear generated by hbm2java
 */
@Entity
@Table(name = "ref_bottom_wear", schema = "public")
public class RefBottomWear implements java.io.Serializable {

	private int id;
	private String bottomWear;

	public RefBottomWear() {
	}

	public RefBottomWear(int id) {
		this.id = id;
	}

	public RefBottomWear(int id, String bottomWear) {
		this.id = id;
		this.bottomWear = bottomWear;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "bottom_wear", length = 20)
	public String getBottomWear() {
		return this.bottomWear;
	}

	public void setBottomWear(String bottomWear) {
		this.bottomWear = bottomWear;
	}

}
