package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefComplexion generated by hbm2java
 */
@Entity
@Table(name = "ref_complexion", schema = "public")
public class RefComplexion implements java.io.Serializable {

	private int id;
	private String name;
	private Set<Profile> profiles = new HashSet<Profile>(0);

	public RefComplexion() {
	}

	public RefComplexion(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public RefComplexion(int id, String name, Set<Profile> profiles) {
		this.id = id;
		this.name = name;
		this.profiles = profiles;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 254)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refComplexion")
	public Set<Profile> getProfiles() {
		return this.profiles;
	}

	public void setProfiles(Set<Profile> profiles) {
		this.profiles = profiles;
	}

}
