package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RefDistrictPoliceEmail generated by hbm2java
 */
@Entity
@Table(name = "ref_district_police_email", schema = "public")
public class RefDistrictPoliceEmail implements java.io.Serializable {

	private int id;
	private String districtId;
	private String emailId;

	public RefDistrictPoliceEmail() {
	}

	public RefDistrictPoliceEmail(int id, String districtId, String emailId) {
		this.id = id;
		this.districtId = districtId;
		this.emailId = emailId;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "district_id", columnDefinition="bpchar(3)", nullable = false, length = 3)
	public String getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(String districtId) {
		this.districtId = districtId;
	}

	@Column(name = "email_id", nullable = false)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

}
