package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * RefDistrict generated by hbm2java
 */
@Entity
@Table(name = "ref_district", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "state_id",
		"district_id" }))
@JsonIdentityInfo(
		  generator = ObjectIdGenerators.PropertyGenerator.class, 
		  property = "districtId")
public class RefDistrict implements java.io.Serializable {

	private String districtId;
	private String stateId;
	private String name;
	private int sno;
	private Set<Profile> profiles = new HashSet<Profile>(0);
	private Set<RefDistrictPoliceMobileNumber> refDistrictPoliceMobileNumbers = new HashSet<RefDistrictPoliceMobileNumber>(
			0);
	private Set<PoliceStationList> policeStationLists = new HashSet<PoliceStationList>(0);

	public RefDistrict() {
	}

	public RefDistrict(String districtId, String stateId, int sno) {
		this.districtId = districtId;
		this.stateId = stateId;
		this.sno = sno;
	}

	public RefDistrict(String districtId, String stateId, String name, int sno, Set<Profile> profiles,
			Set<RefDistrictPoliceMobileNumber> refDistrictPoliceMobileNumbers,
			Set<PoliceStationList> policeStationLists) {
		this.districtId = districtId;
		this.stateId = stateId;
		this.name = name;
		this.sno = sno;
		this.profiles = profiles;
		this.refDistrictPoliceMobileNumbers = refDistrictPoliceMobileNumbers;
		this.policeStationLists = policeStationLists;
	}

	@Id

	@Column(name = "district_id", columnDefinition="bpchar(3)", unique = true, nullable = false, length = 3)
	public String getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(String districtId) {
		this.districtId = districtId;
	}

	@Column(name = "state_id", columnDefinition="bpchar(2)", nullable = false, length = 2)
	public String getStateId() {
		return this.stateId;
	}

	public void setStateId(String stateId) {
		this.stateId = stateId;
	}

	@Column(name = "name", length = 254)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sno", nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refDistrict")
	public Set<Profile> getProfiles() {
		return this.profiles;
	}

	public void setProfiles(Set<Profile> profiles) {
		this.profiles = profiles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refDistrict")
	public Set<RefDistrictPoliceMobileNumber> getRefDistrictPoliceMobileNumbers() {
		return this.refDistrictPoliceMobileNumbers;
	}

	public void setRefDistrictPoliceMobileNumbers(Set<RefDistrictPoliceMobileNumber> refDistrictPoliceMobileNumbers) {
		this.refDistrictPoliceMobileNumbers = refDistrictPoliceMobileNumbers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refDistrict")
	public Set<PoliceStationList> getPoliceStationLists() {
		return this.policeStationLists;
	}

	public void setPoliceStationLists(Set<PoliceStationList> policeStationLists) {
		this.policeStationLists = policeStationLists;
	}

}
