package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RefDistrictPoliceMobileNumber generated by hbm2java
 */
@Entity
@Table(name = "ref_district_police_mobile_number", schema = "public")
public class RefDistrictPoliceMobileNumber implements java.io.Serializable {

	private int id;
	private RefDistrict refDistrict;
	private String mobileNumber;

	public RefDistrictPoliceMobileNumber() {
	}

	public RefDistrictPoliceMobileNumber(int id, RefDistrict refDistrict, String mobileNumber) {
		this.id = id;
		this.refDistrict = refDistrict;
		this.mobileNumber = mobileNumber;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "district_id", columnDefinition="bpchar(3)", nullable = false)
	public RefDistrict getRefDistrict() {
		return this.refDistrict;
	}

	public void setRefDistrict(RefDistrict refDistrict) {
		this.refDistrict = refDistrict;
	}

	@Column(name = "mobile_number", columnDefinition="bpchar(10)", nullable = false, length = 10)
	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

}
