package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RefDistrictTranslation generated by hbm2java
 */
@Entity
@Table(name = "ref_district_translation", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"state_id", "district_id", "language_id" }))
public class RefDistrictTranslation implements java.io.Serializable {

	private int id;
	private String districtId;
	private String stateId;
	private String languageId;
	private String name;

	public RefDistrictTranslation() {
	}

	public RefDistrictTranslation(int id, String districtId, String stateId, String languageId) {
		this.id = id;
		this.districtId = districtId;
		this.stateId = stateId;
		this.languageId = languageId;
	}

	public RefDistrictTranslation(int id, String districtId, String stateId, String languageId, String name) {
		this.id = id;
		this.districtId = districtId;
		this.stateId = stateId;
		this.languageId = languageId;
		this.name = name;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "district_id", columnDefinition="bpchar(3)", nullable = false, length = 3)
	public String getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(String districtId) {
		this.districtId = districtId;
	}

	@Column(name = "state_id", columnDefinition="bpchar(2)", nullable = false, length = 2)
	public String getStateId() {
		return this.stateId;
	}

	public void setStateId(String stateId) {
		this.stateId = stateId;
	}

	@Column(name = "language_id", columnDefinition="bpchar(3)", nullable = false, length = 3)
	public String getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(String languageId) {
		this.languageId = languageId;
	}

	@Column(name = "name", length = 254)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
