package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RefEyeColor generated by hbm2java
 */
@Entity
@Table(name = "ref_eye_color", schema = "public")
public class RefEyeColor implements java.io.Serializable {

	private int id;
	private String name;

	public RefEyeColor() {
	}

	public RefEyeColor(int id, String name) {
		this.id = id;
		this.name = name;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 254)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
