package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RefEyesTypeTranslation generated by hbm2java
 */
@Entity
@Table(name = "ref_eyes_type_translation", schema = "public")
public class RefEyesTypeTranslation implements java.io.Serializable {

	private int id;
	private RefEyesType refEyesType;
	private RefLanguage refLanguage;
	private String name;

	public RefEyesTypeTranslation() {
	}

	public RefEyesTypeTranslation(int id, RefEyesType refEyesType, RefLanguage refLanguage) {
		this.id = id;
		this.refEyesType = refEyesType;
		this.refLanguage = refLanguage;
	}

	public RefEyesTypeTranslation(int id, RefEyesType refEyesType, RefLanguage refLanguage, String name) {
		this.id = id;
		this.refEyesType = refEyesType;
		this.refLanguage = refLanguage;
		this.name = name;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eyes_type_id", nullable = false)
	public RefEyesType getRefEyesType() {
		return this.refEyesType;
	}

	public void setRefEyesType(RefEyesType refEyesType) {
		this.refEyesType = refEyesType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language_id", columnDefinition="bpchar(3)", nullable = false)
	public RefLanguage getRefLanguage() {
		return this.refLanguage;
	}

	public void setRefLanguage(RefLanguage refLanguage) {
		this.refLanguage = refLanguage;
	}

	@Column(name = "name", length = 254)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
