package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RefEyeColorTranslation generated by hbm2java
 */
@Entity
@Table(name = "ref_eye_color_translation", schema = "public")
public class RefEyeColorTranslation implements java.io.Serializable {

	private int id;
	private RefLanguage refLanguage;
	private int eyeColorId;
	private String name;

	public RefEyeColorTranslation() {
	}

	public RefEyeColorTranslation(int id, RefLanguage refLanguage, int eyeColorId) {
		this.id = id;
		this.refLanguage = refLanguage;
		this.eyeColorId = eyeColorId;
	}

	public RefEyeColorTranslation(int id, RefLanguage refLanguage, int eyeColorId, String name) {
		this.id = id;
		this.refLanguage = refLanguage;
		this.eyeColorId = eyeColorId;
		this.name = name;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language_id", columnDefinition="bpchar(3)", nullable = false)
	public RefLanguage getRefLanguage() {
		return this.refLanguage;
	}

	public void setRefLanguage(RefLanguage refLanguage) {
		this.refLanguage = refLanguage;
	}

	@Column(name = "eye_color_id", nullable = false)
	public int getEyeColorId() {
		return this.eyeColorId;
	}

	public void setEyeColorId(int eyeColorId) {
		this.eyeColorId = eyeColorId;
	}

	@Column(name = "name", length = 254)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
