package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefEarsType generated by hbm2java
 */
@Entity
@Table(name = "ref_ears_type", schema = "public")
public class RefEarsType implements java.io.Serializable {

	private int id;
	private String earsType;
	private Set<RefEarsTypeTranslation> refEarsTypeTranslations = new HashSet<RefEarsTypeTranslation>(0);

	public RefEarsType() {
	}

	public RefEarsType(int id) {
		this.id = id;
	}

	public RefEarsType(int id, String earsType, Set<RefEarsTypeTranslation> refEarsTypeTranslations) {
		this.id = id;
		this.earsType = earsType;
		this.refEarsTypeTranslations = refEarsTypeTranslations;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "ears_type", length = 15)
	public String getEarsType() {
		return this.earsType;
	}

	public void setEarsType(String earsType) {
		this.earsType = earsType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refEarsType")
	public Set<RefEarsTypeTranslation> getRefEarsTypeTranslations() {
		return this.refEarsTypeTranslations;
	}

	public void setRefEarsTypeTranslations(Set<RefEarsTypeTranslation> refEarsTypeTranslations) {
		this.refEarsTypeTranslations = refEarsTypeTranslations;
	}

}
