package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * RefFootwear generated by hbm2java
 */
@Entity
@Table(name = "ref_footwear", schema = "public")
@JsonIdentityInfo(
		  generator = ObjectIdGenerators.PropertyGenerator.class, 
		  property = "id")
public class RefFootwear implements java.io.Serializable {

	private int id;
	private String footwear;
	private Set<RefFootwearTranslation> refFootwearTranslations = new HashSet<RefFootwearTranslation>(0);

	public RefFootwear() {
	}

	public RefFootwear(int id) {
		this.id = id;
	}

	public RefFootwear(int id, String footwear, Set<RefFootwearTranslation> refFootwearTranslations) {
		this.id = id;
		this.footwear = footwear;
		this.refFootwearTranslations = refFootwearTranslations;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "footwear", length = 15)
	public String getFootwear() {
		return this.footwear;
	}

	public void setFootwear(String footwear) {
		this.footwear = footwear;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refFootwear")
	public Set<RefFootwearTranslation> getRefFootwearTranslations() {
		return this.refFootwearTranslations;
	}

	public void setRefFootwearTranslations(Set<RefFootwearTranslation> refFootwearTranslations) {
		this.refFootwearTranslations = refFootwearTranslations;
	}

}
