package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefFrontTeeths generated by hbm2java
 */
@Entity
@Table(name = "ref_front_teeths", schema = "public")
public class RefFrontTeeths implements java.io.Serializable {

	private int id;
	private String frontTeeths;
	private Set<RefFrontTeethsTranslation> refFrontTeethsTranslations = new HashSet<RefFrontTeethsTranslation>(0);

	public RefFrontTeeths() {
	}

	public RefFrontTeeths(int id) {
		this.id = id;
	}

	public RefFrontTeeths(int id, String frontTeeths, Set<RefFrontTeethsTranslation> refFrontTeethsTranslations) {
		this.id = id;
		this.frontTeeths = frontTeeths;
		this.refFrontTeethsTranslations = refFrontTeethsTranslations;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "front_teeths", length = 15)
	public String getFrontTeeths() {
		return this.frontTeeths;
	}

	public void setFrontTeeths(String frontTeeths) {
		this.frontTeeths = frontTeeths;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refFrontTeeths")
	public Set<RefFrontTeethsTranslation> getRefFrontTeethsTranslations() {
		return this.refFrontTeethsTranslations;
	}

	public void setRefFrontTeethsTranslations(Set<RefFrontTeethsTranslation> refFrontTeethsTranslations) {
		this.refFrontTeethsTranslations = refFrontTeethsTranslations;
	}

}
