package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefHealth generated by hbm2java
 */
@Entity
@Table(name = "ref_health", schema = "public")
public class RefHealth implements java.io.Serializable {

	private int id;
	private String health;
	private Set<RefHealthTranslation> refHealthTranslations = new HashSet<RefHealthTranslation>(0);

	public RefHealth() {
	}

	public RefHealth(int id) {
		this.id = id;
	}

	public RefHealth(int id, String health, Set<RefHealthTranslation> refHealthTranslations) {
		this.id = id;
		this.health = health;
		this.refHealthTranslations = refHealthTranslations;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "health", length = 50)
	public String getHealth() {
		return this.health;
	}

	public void setHealth(String health) {
		this.health = health;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refHealth")
	public Set<RefHealthTranslation> getRefHealthTranslations() {
		return this.refHealthTranslations;
	}

	public void setRefHealthTranslations(Set<RefHealthTranslation> refHealthTranslations) {
		this.refHealthTranslations = refHealthTranslations;
	}

}
