package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * RefHairSize generated by hbm2java
 */
@Entity
@Table(name = "ref_hair_size", schema = "public")
@JsonIdentityInfo(
		  generator = ObjectIdGenerators.PropertyGenerator.class, 
		  property = "id")
public class RefHairSize implements java.io.Serializable {

	private int id;
	private String hairSize;
	private Set<RefHairSizeTranslation> refHairSizeTranslations = new HashSet<RefHairSizeTranslation>(0);

	public RefHairSize() {
	}

	public RefHairSize(int id) {
		this.id = id;
	}

	public RefHairSize(int id, String hairSize, Set<RefHairSizeTranslation> refHairSizeTranslations) {
		this.id = id;
		this.hairSize = hairSize;
		this.refHairSizeTranslations = refHairSizeTranslations;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "hair_size", length = 15)
	public String getHairSize() {
		return this.hairSize;
	}

	public void setHairSize(String hairSize) {
		this.hairSize = hairSize;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refHairSize")
	public Set<RefHairSizeTranslation> getRefHairSizeTranslations() {
		return this.refHairSizeTranslations;
	}

	public void setRefHairSizeTranslations(Set<RefHairSizeTranslation> refHairSizeTranslations) {
		this.refHairSizeTranslations = refHairSizeTranslations;
	}

}
