package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RefHeightInches generated by hbm2java
 */
@Entity
@Table(name = "ref_height_inches", schema = "public")
public class RefHeightInches implements java.io.Serializable {

	private int id;
	private Integer inches;

	public RefHeightInches() {
	}

	public RefHeightInches(int id) {
		this.id = id;
	}

	public RefHeightInches(int id, Integer inches) {
		this.id = id;
		this.inches = inches;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "inches")
	public Integer getInches() {
		return this.inches;
	}

	public void setInches(Integer inches) {
		this.inches = inches;
	}

}
