package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefInternetMediaSubType generated by hbm2java
 */
@Entity
@Table(name = "ref_internet_media_sub_type", schema = "public")
public class RefInternetMediaSubType implements java.io.Serializable {

	private int id;
	private RefInternetMediaType refInternetMediaType;
	private String name;
	private Set<Media> medias = new HashSet<Media>(0);

	public RefInternetMediaSubType() {
	}

	public RefInternetMediaSubType(int id, RefInternetMediaType refInternetMediaType) {
		this.id = id;
		this.refInternetMediaType = refInternetMediaType;
	}

	public RefInternetMediaSubType(int id, RefInternetMediaType refInternetMediaType, String name, Set<Media> medias) {
		this.id = id;
		this.refInternetMediaType = refInternetMediaType;
		this.name = name;
		this.medias = medias;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_id", nullable = false)
	public RefInternetMediaType getRefInternetMediaType() {
		return this.refInternetMediaType;
	}

	public void setRefInternetMediaType(RefInternetMediaType refInternetMediaType) {
		this.refInternetMediaType = refInternetMediaType;
	}

	@Column(name = "name", length = 254)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refInternetMediaSubType")
	public Set<Media> getMedias() {
		return this.medias;
	}

	public void setMedias(Set<Media> medias) {
		this.medias = medias;
	}

}
