package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefInternetMediaType generated by hbm2java
 */
@Entity
@Table(name = "ref_internet_media_type", schema = "public")
public class RefInternetMediaType implements java.io.Serializable {

	private int id;
	private String name;
	private Set<RefInternetMediaSubType> refInternetMediaSubTypes = new HashSet<RefInternetMediaSubType>(0);
	private Set<Media> medias = new HashSet<Media>(0);

	public RefInternetMediaType() {
	}

	public RefInternetMediaType(int id) {
		this.id = id;
	}

	public RefInternetMediaType(int id, String name, Set<RefInternetMediaSubType> refInternetMediaSubTypes,
			Set<Media> medias) {
		this.id = id;
		this.name = name;
		this.refInternetMediaSubTypes = refInternetMediaSubTypes;
		this.medias = medias;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 254)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refInternetMediaType")
	public Set<RefInternetMediaSubType> getRefInternetMediaSubTypes() {
		return this.refInternetMediaSubTypes;
	}

	public void setRefInternetMediaSubTypes(Set<RefInternetMediaSubType> refInternetMediaSubTypes) {
		this.refInternetMediaSubTypes = refInternetMediaSubTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refInternetMediaType")
	public Set<Media> getMedias() {
		return this.medias;
	}

	public void setMedias(Set<Media> medias) {
		this.medias = medias;
	}

}
