package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * RefLanguage generated by hbm2java
 */
//@Entity
@Table(name = "ref_language", schema = "public")
@JsonIdentityInfo(
		  generator = ObjectIdGenerators.PropertyGenerator.class, 
		  property = "id")
public class RefLanguage implements java.io.Serializable {

	private String id;
	private String part2b;
	private String part2t;
	private String part1;
	private char scope;
	private char languageType;
	private String refName;
	private String comment;
	private Set<RefModerationStatusTranslation> refModerationStatusTranslations = new HashSet<RefModerationStatusTranslation>(
			0);
	private Set<RefFrontTeethsTranslation> refFrontTeethsTranslations = new HashSet<RefFrontTeethsTranslation>(0);
	private Set<RefProfileLanguageTranslation> refProfileLanguageTranslations = new HashSet<RefProfileLanguageTranslation>(
			0);
	private Set<RefBuildTranslation> refBuildTranslations = new HashSet<RefBuildTranslation>(0);
	private Set<RefEyeColorTranslation> refEyeColorTranslations = new HashSet<RefEyeColorTranslation>(0);
	private Set<RefHairColorTranslation> refHairColorTranslations = new HashSet<RefHairColorTranslation>(0);
	private Set<RefFootwearTranslation> refFootwearTranslations = new HashSet<RefFootwearTranslation>(0);
	private Set<RefHairSizeTranslation> refHairSizeTranslations = new HashSet<RefHairSizeTranslation>(0);
	private Set<RefBottomWearTranslation> refBottomWearTranslations = new HashSet<RefBottomWearTranslation>(0);
	private Set<RefColorTranslation> refColorTranslations = new HashSet<RefColorTranslation>(0);
	private Set<RefStateTranslation> refStateTranslations = new HashSet<RefStateTranslation>(0);
	private Set<RefTopWearTranslation> refTopWearTranslations = new HashSet<RefTopWearTranslation>(0);
	private Set<ProfileTextualDetail> profileTextualDetails = new HashSet<ProfileTextualDetail>(0);
	private Set<RefEarsSizeTranslation> refEarsSizeTranslations = new HashSet<RefEarsSizeTranslation>(0);
	private Set<RefEarsTypeTranslation> refEarsTypeTranslations = new HashSet<RefEarsTypeTranslation>(0);
	private Set<RefSpectaclesTypeTranslation> refSpectaclesTypeTranslations = new HashSet<RefSpectaclesTypeTranslation>(
			0);
	private Set<RefComplextionTranslation> refComplextionTranslations = new HashSet<RefComplextionTranslation>(0);
	private Set<RefNeckTypeTranslation> refNeckTypeTranslations = new HashSet<RefNeckTypeTranslation>(0);
	private Set<RefGenderTranslation> refGenderTranslations = new HashSet<RefGenderTranslation>(0);
	private Set<RefRelationshipTranslation> refRelationshipTranslations = new HashSet<RefRelationshipTranslation>(0);
	private Set<RefLipsTypeTranslation> refLipsTypeTranslations = new HashSet<RefLipsTypeTranslation>(0);
	private Set<RefLipsColorTranslation> refLipsColorTranslations = new HashSet<RefLipsColorTranslation>(0);
	private Set<RefEyesTypeTranslation> refEyesTypeTranslations = new HashSet<RefEyesTypeTranslation>(0);
	private Set<RefSpeechTranslation> refSpeechTranslations = new HashSet<RefSpeechTranslation>(0);

	public RefLanguage() {
	}

	public RefLanguage(String id, char scope, char languageType, String refName) {
		this.id = id;
		this.scope = scope;
		this.languageType = languageType;
		this.refName = refName;
	}

	public RefLanguage(String id, String part2b, String part2t, String part1, char scope, char languageType,
			String refName, String comment, Set<RefModerationStatusTranslation> refModerationStatusTranslations,
			Set<RefFrontTeethsTranslation> refFrontTeethsTranslations,
			Set<RefProfileLanguageTranslation> refProfileLanguageTranslations,
			Set<RefBuildTranslation> refBuildTranslations, Set<RefEyeColorTranslation> refEyeColorTranslations,
			Set<RefHairColorTranslation> refHairColorTranslations, Set<RefFootwearTranslation> refFootwearTranslations,
			Set<RefHairSizeTranslation> refHairSizeTranslations,
			Set<RefBottomWearTranslation> refBottomWearTranslations, Set<RefColorTranslation> refColorTranslations,
			Set<RefStateTranslation> refStateTranslations, Set<RefTopWearTranslation> refTopWearTranslations,
			Set<ProfileTextualDetail> profileTextualDetails, Set<RefEarsSizeTranslation> refEarsSizeTranslations,
			Set<RefEarsTypeTranslation> refEarsTypeTranslations,
			Set<RefSpectaclesTypeTranslation> refSpectaclesTypeTranslations,
			Set<RefComplextionTranslation> refComplextionTranslations,
			Set<RefNeckTypeTranslation> refNeckTypeTranslations, Set<RefGenderTranslation> refGenderTranslations,
			Set<RefRelationshipTranslation> refRelationshipTranslations,
			Set<RefLipsTypeTranslation> refLipsTypeTranslations, Set<RefLipsColorTranslation> refLipsColorTranslations,
			Set<RefEyesTypeTranslation> refEyesTypeTranslations, Set<RefSpeechTranslation> refSpeechTranslations) {
		this.id = id;
		this.part2b = part2b;
		this.part2t = part2t;
		this.part1 = part1;
		this.scope = scope;
		this.languageType = languageType;
		this.refName = refName;
		this.comment = comment;
		this.refModerationStatusTranslations = refModerationStatusTranslations;
		this.refFrontTeethsTranslations = refFrontTeethsTranslations;
		this.refProfileLanguageTranslations = refProfileLanguageTranslations;
		this.refBuildTranslations = refBuildTranslations;
		this.refEyeColorTranslations = refEyeColorTranslations;
		this.refHairColorTranslations = refHairColorTranslations;
		this.refFootwearTranslations = refFootwearTranslations;
		this.refHairSizeTranslations = refHairSizeTranslations;
		this.refBottomWearTranslations = refBottomWearTranslations;
		this.refColorTranslations = refColorTranslations;
		this.refStateTranslations = refStateTranslations;
		this.refTopWearTranslations = refTopWearTranslations;
		this.profileTextualDetails = profileTextualDetails;
		this.refEarsSizeTranslations = refEarsSizeTranslations;
		this.refEarsTypeTranslations = refEarsTypeTranslations;
		this.refSpectaclesTypeTranslations = refSpectaclesTypeTranslations;
		this.refComplextionTranslations = refComplextionTranslations;
		this.refNeckTypeTranslations = refNeckTypeTranslations;
		this.refGenderTranslations = refGenderTranslations;
		this.refRelationshipTranslations = refRelationshipTranslations;
		this.refLipsTypeTranslations = refLipsTypeTranslations;
		this.refLipsColorTranslations = refLipsColorTranslations;
		this.refEyesTypeTranslations = refEyesTypeTranslations;
		this.refSpeechTranslations = refSpeechTranslations;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false, length = 3)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "part2b", columnDefinition="bpchar(3)", length = 3)
	public String getPart2b() {
		return this.part2b;
	}

	public void setPart2b(String part2b) {
		this.part2b = part2b;
	}

	@Column(name = "part2t", columnDefinition="bpchar(3)", length = 3)
	public String getPart2t() {
		return this.part2t;
	}

	public void setPart2t(String part2t) {
		this.part2t = part2t;
	}

	@Column(name = "part1", columnDefinition="bpchar(2)", length = 2)
	public String getPart1() {
		return this.part1;
	}

	public void setPart1(String part1) {
		this.part1 = part1;
	}

	@Column(name = "scope", nullable = false, length = 1)
	public char getScope() {
		return this.scope;
	}

	public void setScope(char scope) {
		this.scope = scope;
	}

	@Column(name = "language_type", nullable = false, length = 1)
	public char getLanguageType() {
		return this.languageType;
	}

	public void setLanguageType(char languageType) {
		this.languageType = languageType;
	}

	@Column(name = "ref_name", nullable = false)
	public String getRefName() {
		return this.refName;
	}

	public void setRefName(String refName) {
		this.refName = refName;
	}

	@Column(name = "comment")
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguage")
	public Set<RefModerationStatusTranslation> getRefModerationStatusTranslations() {
		return this.refModerationStatusTranslations;
	}

	public void setRefModerationStatusTranslations(
			Set<RefModerationStatusTranslation> refModerationStatusTranslations) {
		this.refModerationStatusTranslations = refModerationStatusTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguage")
	public Set<RefFrontTeethsTranslation> getRefFrontTeethsTranslations() {
		return this.refFrontTeethsTranslations;
	}

	public void setRefFrontTeethsTranslations(Set<RefFrontTeethsTranslation> refFrontTeethsTranslations) {
		this.refFrontTeethsTranslations = refFrontTeethsTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguage")
	public Set<RefProfileLanguageTranslation> getRefProfileLanguageTranslations() {
		return this.refProfileLanguageTranslations;
	}

	public void setRefProfileLanguageTranslations(Set<RefProfileLanguageTranslation> refProfileLanguageTranslations) {
		this.refProfileLanguageTranslations = refProfileLanguageTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguage")
	public Set<RefBuildTranslation> getRefBuildTranslations() {
		return this.refBuildTranslations;
	}

	public void setRefBuildTranslations(Set<RefBuildTranslation> refBuildTranslations) {
		this.refBuildTranslations = refBuildTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguage")
	public Set<RefEyeColorTranslation> getRefEyeColorTranslations() {
		return this.refEyeColorTranslations;
	}

	public void setRefEyeColorTranslations(Set<RefEyeColorTranslation> refEyeColorTranslations) {
		this.refEyeColorTranslations = refEyeColorTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguage")
	public Set<RefHairColorTranslation> getRefHairColorTranslations() {
		return this.refHairColorTranslations;
	}

	public void setRefHairColorTranslations(Set<RefHairColorTranslation> refHairColorTranslations) {
		this.refHairColorTranslations = refHairColorTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguage")
	public Set<RefFootwearTranslation> getRefFootwearTranslations() {
		return this.refFootwearTranslations;
	}

	public void setRefFootwearTranslations(Set<RefFootwearTranslation> refFootwearTranslations) {
		this.refFootwearTranslations = refFootwearTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguage")
	public Set<RefHairSizeTranslation> getRefHairSizeTranslations() {
		return this.refHairSizeTranslations;
	}

	public void setRefHairSizeTranslations(Set<RefHairSizeTranslation> refHairSizeTranslations) {
		this.refHairSizeTranslations = refHairSizeTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguage")
	public Set<RefBottomWearTranslation> getRefBottomWearTranslations() {
		return this.refBottomWearTranslations;
	}

	public void setRefBottomWearTranslations(Set<RefBottomWearTranslation> refBottomWearTranslations) {
		this.refBottomWearTranslations = refBottomWearTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguage")
	public Set<RefColorTranslation> getRefColorTranslations() {
		return this.refColorTranslations;
	}

	public void setRefColorTranslations(Set<RefColorTranslation> refColorTranslations) {
		this.refColorTranslations = refColorTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguage")
	public Set<RefStateTranslation> getRefStateTranslations() {
		return this.refStateTranslations;
	}

	public void setRefStateTranslations(Set<RefStateTranslation> refStateTranslations) {
		this.refStateTranslations = refStateTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguage")
	public Set<RefTopWearTranslation> getRefTopWearTranslations() {
		return this.refTopWearTranslations;
	}

	public void setRefTopWearTranslations(Set<RefTopWearTranslation> refTopWearTranslations) {
		this.refTopWearTranslations = refTopWearTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguage")
	public Set<ProfileTextualDetail> getProfileTextualDetails() {
		return this.profileTextualDetails;
	}

	public void setProfileTextualDetails(Set<ProfileTextualDetail> profileTextualDetails) {
		this.profileTextualDetails = profileTextualDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguage")
	public Set<RefEarsSizeTranslation> getRefEarsSizeTranslations() {
		return this.refEarsSizeTranslations;
	}

	public void setRefEarsSizeTranslations(Set<RefEarsSizeTranslation> refEarsSizeTranslations) {
		this.refEarsSizeTranslations = refEarsSizeTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguage")
	public Set<RefEarsTypeTranslation> getRefEarsTypeTranslations() {
		return this.refEarsTypeTranslations;
	}

	public void setRefEarsTypeTranslations(Set<RefEarsTypeTranslation> refEarsTypeTranslations) {
		this.refEarsTypeTranslations = refEarsTypeTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguage")
	public Set<RefSpectaclesTypeTranslation> getRefSpectaclesTypeTranslations() {
		return this.refSpectaclesTypeTranslations;
	}

	public void setRefSpectaclesTypeTranslations(Set<RefSpectaclesTypeTranslation> refSpectaclesTypeTranslations) {
		this.refSpectaclesTypeTranslations = refSpectaclesTypeTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguage")
	public Set<RefComplextionTranslation> getRefComplextionTranslations() {
		return this.refComplextionTranslations;
	}

	public void setRefComplextionTranslations(Set<RefComplextionTranslation> refComplextionTranslations) {
		this.refComplextionTranslations = refComplextionTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguage")
	public Set<RefNeckTypeTranslation> getRefNeckTypeTranslations() {
		return this.refNeckTypeTranslations;
	}

	public void setRefNeckTypeTranslations(Set<RefNeckTypeTranslation> refNeckTypeTranslations) {
		this.refNeckTypeTranslations = refNeckTypeTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguage")
	public Set<RefGenderTranslation> getRefGenderTranslations() {
		return this.refGenderTranslations;
	}

	public void setRefGenderTranslations(Set<RefGenderTranslation> refGenderTranslations) {
		this.refGenderTranslations = refGenderTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguage")
	public Set<RefRelationshipTranslation> getRefRelationshipTranslations() {
		return this.refRelationshipTranslations;
	}

	public void setRefRelationshipTranslations(Set<RefRelationshipTranslation> refRelationshipTranslations) {
		this.refRelationshipTranslations = refRelationshipTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguage")
	public Set<RefLipsTypeTranslation> getRefLipsTypeTranslations() {
		return this.refLipsTypeTranslations;
	}

	public void setRefLipsTypeTranslations(Set<RefLipsTypeTranslation> refLipsTypeTranslations) {
		this.refLipsTypeTranslations = refLipsTypeTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguage")
	public Set<RefLipsColorTranslation> getRefLipsColorTranslations() {
		return this.refLipsColorTranslations;
	}

	public void setRefLipsColorTranslations(Set<RefLipsColorTranslation> refLipsColorTranslations) {
		this.refLipsColorTranslations = refLipsColorTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguage")
	public Set<RefEyesTypeTranslation> getRefEyesTypeTranslations() {
		return this.refEyesTypeTranslations;
	}

	public void setRefEyesTypeTranslations(Set<RefEyesTypeTranslation> refEyesTypeTranslations) {
		this.refEyesTypeTranslations = refEyesTypeTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguage")
	public Set<RefSpeechTranslation> getRefSpeechTranslations() {
		return this.refSpeechTranslations;
	}

	public void setRefSpeechTranslations(Set<RefSpeechTranslation> refSpeechTranslations) {
		this.refSpeechTranslations = refSpeechTranslations;
	}

}
