package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefLipsType generated by hbm2java
 */
@Entity
@Table(name = "ref_lips_type", schema = "public")
public class RefLipsType implements java.io.Serializable {

	private int id;
	private String lipsType;
	private Set<RefLipsTypeTranslation> refLipsTypeTranslations = new HashSet<RefLipsTypeTranslation>(0);

	public RefLipsType() {
	}

	public RefLipsType(int id) {
		this.id = id;
	}

	public RefLipsType(int id, String lipsType, Set<RefLipsTypeTranslation> refLipsTypeTranslations) {
		this.id = id;
		this.lipsType = lipsType;
		this.refLipsTypeTranslations = refLipsTypeTranslations;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "lips_type", length = 15)
	public String getLipsType() {
		return this.lipsType;
	}

	public void setLipsType(String lipsType) {
		this.lipsType = lipsType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLipsType")
	public Set<RefLipsTypeTranslation> getRefLipsTypeTranslations() {
		return this.refLipsTypeTranslations;
	}

	public void setRefLipsTypeTranslations(Set<RefLipsTypeTranslation> refLipsTypeTranslations) {
		this.refLipsTypeTranslations = refLipsTypeTranslations;
	}

}
