package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefLipsColor generated by hbm2java
 */
@Entity
@Table(name = "ref_lips_color", schema = "public")
public class RefLipsColor implements java.io.Serializable {

	private int id;
	private String lipsColor;
	private Set<RefLipsColorTranslation> refLipsColorTranslations = new HashSet<RefLipsColorTranslation>(0);

	public RefLipsColor() {
	}

	public RefLipsColor(int id) {
		this.id = id;
	}

	public RefLipsColor(int id, String lipsColor, Set<RefLipsColorTranslation> refLipsColorTranslations) {
		this.id = id;
		this.lipsColor = lipsColor;
		this.refLipsColorTranslations = refLipsColorTranslations;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "lips_color", length = 15)
	public String getLipsColor() {
		return this.lipsColor;
	}

	public void setLipsColor(String lipsColor) {
		this.lipsColor = lipsColor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLipsColor")
	public Set<RefLipsColorTranslation> getRefLipsColorTranslations() {
		return this.refLipsColorTranslations;
	}

	public void setRefLipsColorTranslations(Set<RefLipsColorTranslation> refLipsColorTranslations) {
		this.refLipsColorTranslations = refLipsColorTranslations;
	}

}
