package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RefLipsTypeTranslation generated by hbm2java
 */
@Entity
@Table(name = "ref_lips_type_translation", schema = "public")
public class RefLipsTypeTranslation implements java.io.Serializable {

	private int id;
	private RefLanguage refLanguage;
	private RefLipsType refLipsType;
	private String name;

	public RefLipsTypeTranslation() {
	}

	public RefLipsTypeTranslation(int id, RefLanguage refLanguage, RefLipsType refLipsType) {
		this.id = id;
		this.refLanguage = refLanguage;
		this.refLipsType = refLipsType;
	}

	public RefLipsTypeTranslation(int id, RefLanguage refLanguage, RefLipsType refLipsType, String name) {
		this.id = id;
		this.refLanguage = refLanguage;
		this.refLipsType = refLipsType;
		this.name = name;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language_id", columnDefinition="bpchar(3)", nullable = false)
	public RefLanguage getRefLanguage() {
		return this.refLanguage;
	}

	public void setRefLanguage(RefLanguage refLanguage) {
		this.refLanguage = refLanguage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lips_type_id", nullable = false)
	public RefLipsType getRefLipsType() {
		return this.refLipsType;
	}

	public void setRefLipsType(RefLipsType refLipsType) {
		this.refLipsType = refLipsType;
	}

	@Column(name = "name", length = 254)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
