package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * RefModerationStatusTranslation generated by hbm2java
 */
@Entity
@Table(name = "ref_moderation_status_translation", schema = "public")
@JsonIdentityInfo(
		  generator = ObjectIdGenerators.PropertyGenerator.class, 
		  property = "id")
public class RefModerationStatusTranslation implements java.io.Serializable {

	private int id;
	private RefLanguage refLanguage;
	private RefModerationStatus refModerationStatus;
	private String name;

	public RefModerationStatusTranslation() {
	}

	public RefModerationStatusTranslation(int id, RefLanguage refLanguage, RefModerationStatus refModerationStatus) {
		this.id = id;
		this.refLanguage = refLanguage;
		this.refModerationStatus = refModerationStatus;
	}

	public RefModerationStatusTranslation(int id, RefLanguage refLanguage, RefModerationStatus refModerationStatus,
			String name) {
		this.id = id;
		this.refLanguage = refLanguage;
		this.refModerationStatus = refModerationStatus;
		this.name = name;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language_id", columnDefinition="bpchar(3)", nullable = false)
	public RefLanguage getRefLanguage() {
		return this.refLanguage;
	}

	public void setRefLanguage(RefLanguage refLanguage) {
		this.refLanguage = refLanguage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "moderation_status", nullable = false)
	public RefModerationStatus getRefModerationStatus() {
		return this.refModerationStatus;
	}

	public void setRefModerationStatus(RefModerationStatus refModerationStatus) {
		this.refModerationStatus = refModerationStatus;
	}

	@Column(name = "name", length = 254)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
