package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * RefModerationStatus generated by hbm2java
 */
@Entity
@Table(name = "ref_moderation_status", schema = "public")
@JsonIdentityInfo(
		  generator = ObjectIdGenerators.PropertyGenerator.class, 
		  property = "id")
public class RefModerationStatus implements java.io.Serializable {

	private int id;
	private String name;
	private Set<RefModerationStatusTranslation> refModerationStatusTranslations = new HashSet<RefModerationStatusTranslation>(
			0);
	private Set<Profile> profiles = new HashSet<Profile>(0);

	public RefModerationStatus() {
	}

	public RefModerationStatus(int id) {
		this.id = id;
	}

	public RefModerationStatus(int id, String name, Set<RefModerationStatusTranslation> refModerationStatusTranslations,
			Set<Profile> profiles) {
		this.id = id;
		this.name = name;
		this.refModerationStatusTranslations = refModerationStatusTranslations;
		this.profiles = profiles;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 254)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refModerationStatus")
	public Set<RefModerationStatusTranslation> getRefModerationStatusTranslations() {
		return this.refModerationStatusTranslations;
	}

	public void setRefModerationStatusTranslations(
			Set<RefModerationStatusTranslation> refModerationStatusTranslations) {
		this.refModerationStatusTranslations = refModerationStatusTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refModerationStatus")
	public Set<Profile> getProfiles() {
		return this.profiles;
	}

	public void setProfiles(Set<Profile> profiles) {
		this.profiles = profiles;
	}

}
