package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefNcrbPoliceStation generated by hbm2java
 */
@Entity
@Table(name = "ref_ncrb_police_station", schema = "public")
public class RefNcrbPoliceStation implements java.io.Serializable {

	private String ncrbPoliceStationId;
	private String ncrbPoliceStationName;
	private Set<Profile> profiles = new HashSet<Profile>(0);

	public RefNcrbPoliceStation() {
	}

	public RefNcrbPoliceStation(String ncrbPoliceStationId) {
		this.ncrbPoliceStationId = ncrbPoliceStationId;
	}

	public RefNcrbPoliceStation(String ncrbPoliceStationId, String ncrbPoliceStationName, Set<Profile> profiles) {
		this.ncrbPoliceStationId = ncrbPoliceStationId;
		this.ncrbPoliceStationName = ncrbPoliceStationName;
		this.profiles = profiles;
	}

	@Id

	@Column(name = "ncrb_police_station_id", unique = true, nullable = false, length = 7)
	public String getNcrbPoliceStationId() {
		return this.ncrbPoliceStationId;
	}

	public void setNcrbPoliceStationId(String ncrbPoliceStationId) {
		this.ncrbPoliceStationId = ncrbPoliceStationId;
	}

	@Column(name = "ncrb_police_station_name")
	public String getNcrbPoliceStationName() {
		return this.ncrbPoliceStationName;
	}

	public void setNcrbPoliceStationName(String ncrbPoliceStationName) {
		this.ncrbPoliceStationName = ncrbPoliceStationName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refNcrbPoliceStation")
	public Set<Profile> getProfiles() {
		return this.profiles;
	}

	public void setProfiles(Set<Profile> profiles) {
		this.profiles = profiles;
	}

}
