package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefNcrbState generated by hbm2java
 */
@Entity
@Table(name = "ref_ncrb_state", schema = "public")
public class RefNcrbState implements java.io.Serializable {

	private String ncrbStateId;
	private String ncrbStateName;
	private Set<Profile> profiles = new HashSet<Profile>(0);

	public RefNcrbState() {
	}

	public RefNcrbState(String ncrbStateId) {
		this.ncrbStateId = ncrbStateId;
	}

	public RefNcrbState(String ncrbStateId, String ncrbStateName, Set<Profile> profiles) {
		this.ncrbStateId = ncrbStateId;
		this.ncrbStateName = ncrbStateName;
		this.profiles = profiles;
	}

	@Id

	@Column(name = "ncrb_state_id", unique = true, nullable = false, length = 2)
	public String getNcrbStateId() {
		return this.ncrbStateId;
	}

	public void setNcrbStateId(String ncrbStateId) {
		this.ncrbStateId = ncrbStateId;
	}

	@Column(name = "ncrb_state_name")
	public String getNcrbStateName() {
		return this.ncrbStateName;
	}

	public void setNcrbStateName(String ncrbStateName) {
		this.ncrbStateName = ncrbStateName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refNcrbState")
	public Set<Profile> getProfiles() {
		return this.profiles;
	}

	public void setProfiles(Set<Profile> profiles) {
		this.profiles = profiles;
	}

}
