package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefNeckType generated by hbm2java
 */
@Entity
@Table(name = "ref_neck_type", schema = "public")
public class RefNeckType implements java.io.Serializable {

	private int id;
	private String neckType;
	private Set<RefNeckTypeTranslation> refNeckTypeTranslations = new HashSet<RefNeckTypeTranslation>(0);

	public RefNeckType() {
	}

	public RefNeckType(int id) {
		this.id = id;
	}

	public RefNeckType(int id, String neckType, Set<RefNeckTypeTranslation> refNeckTypeTranslations) {
		this.id = id;
		this.neckType = neckType;
		this.refNeckTypeTranslations = refNeckTypeTranslations;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "neck_type", length = 15)
	public String getNeckType() {
		return this.neckType;
	}

	public void setNeckType(String neckType) {
		this.neckType = neckType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refNeckType")
	public Set<RefNeckTypeTranslation> getRefNeckTypeTranslations() {
		return this.refNeckTypeTranslations;
	}

	public void setRefNeckTypeTranslations(Set<RefNeckTypeTranslation> refNeckTypeTranslations) {
		this.refNeckTypeTranslations = refNeckTypeTranslations;
	}

}
