package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefNcrbDistrict generated by hbm2java
 */
@Entity
@Table(name = "ref_ncrb_district", schema = "public")
public class RefNcrbDistrict implements java.io.Serializable {

	private String ncrbDistrictId;
	private String ncrbDistrictName;
	private Set<Profile> profiles = new HashSet<Profile>(0);

	public RefNcrbDistrict() {
	}

	public RefNcrbDistrict(String ncrbDistrictId) {
		this.ncrbDistrictId = ncrbDistrictId;
	}

	public RefNcrbDistrict(String ncrbDistrictId, String ncrbDistrictName, Set<Profile> profiles) {
		this.ncrbDistrictId = ncrbDistrictId;
		this.ncrbDistrictName = ncrbDistrictName;
		this.profiles = profiles;
	}

	@Id

	@Column(name = "ncrb_district_id", unique = true, nullable = false, length = 5)
	public String getNcrbDistrictId() {
		return this.ncrbDistrictId;
	}

	public void setNcrbDistrictId(String ncrbDistrictId) {
		this.ncrbDistrictId = ncrbDistrictId;
	}

	@Column(name = "ncrb_district_name")
	public String getNcrbDistrictName() {
		return this.ncrbDistrictName;
	}

	public void setNcrbDistrictName(String ncrbDistrictName) {
		this.ncrbDistrictName = ncrbDistrictName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refNcrbDistrict")
	public Set<Profile> getProfiles() {
		return this.profiles;
	}

	public void setProfiles(Set<Profile> profiles) {
		this.profiles = profiles;
	}

}
