package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RefNeckTypeTranslation generated by hbm2java
 */
@Entity
@Table(name = "ref_neck_type_translation", schema = "public")
public class RefNeckTypeTranslation implements java.io.Serializable {

	private int id;
	private RefLanguage refLanguage;
	private RefNeckType refNeckType;
	private String name;

	public RefNeckTypeTranslation() {
	}

	public RefNeckTypeTranslation(int id, RefLanguage refLanguage, RefNeckType refNeckType) {
		this.id = id;
		this.refLanguage = refLanguage;
		this.refNeckType = refNeckType;
	}

	public RefNeckTypeTranslation(int id, RefLanguage refLanguage, RefNeckType refNeckType, String name) {
		this.id = id;
		this.refLanguage = refLanguage;
		this.refNeckType = refNeckType;
		this.name = name;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language_id", columnDefinition="bpchar(3)", nullable = false)
	public RefLanguage getRefLanguage() {
		return this.refLanguage;
	}

	public void setRefLanguage(RefLanguage refLanguage) {
		this.refLanguage = refLanguage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "neck_type_id", nullable = false)
	public RefNeckType getRefNeckType() {
		return this.refNeckType;
	}

	public void setRefNeckType(RefNeckType refNeckType) {
		this.refNeckType = refNeckType;
	}

	@Column(name = "name", length = 254)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
