package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RefOtherKnownLanguages generated by hbm2java
 */
@Entity
@Table(name = "ref_other_known_languages", schema = "public")
public class RefOtherKnownLanguages implements java.io.Serializable {

	private int id;
	private String otherKnownLanguages;

	public RefOtherKnownLanguages() {
	}

	public RefOtherKnownLanguages(int id) {
		this.id = id;
	}

	public RefOtherKnownLanguages(int id, String otherKnownLanguages) {
		this.id = id;
		this.otherKnownLanguages = otherKnownLanguages;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "other_known_languages", length = 15)
	public String getOtherKnownLanguages() {
		return this.otherKnownLanguages;
	}

	public void setOtherKnownLanguages(String otherKnownLanguages) {
		this.otherKnownLanguages = otherKnownLanguages;
	}

}
