package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RefProfileLanguageTranslation generated by hbm2java
 */
@Entity
@Table(name = "ref_profile_language_translation", schema = "public")
public class RefProfileLanguageTranslation implements java.io.Serializable {

	private int id;
	private RefLanguage refLanguage;
	private RefProfileLanguage refProfileLanguage;
	private String name;

	public RefProfileLanguageTranslation() {
	}

	public RefProfileLanguageTranslation(int id, RefLanguage refLanguage, RefProfileLanguage refProfileLanguage) {
		this.id = id;
		this.refLanguage = refLanguage;
		this.refProfileLanguage = refProfileLanguage;
	}

	public RefProfileLanguageTranslation(int id, RefLanguage refLanguage, RefProfileLanguage refProfileLanguage,
			String name) {
		this.id = id;
		this.refLanguage = refLanguage;
		this.refProfileLanguage = refProfileLanguage;
		this.name = name;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language_id", columnDefinition="bpchar(3)", nullable = false)
	public RefLanguage getRefLanguage() {
		return this.refLanguage;
	}

	public void setRefLanguage(RefLanguage refLanguage) {
		this.refLanguage = refLanguage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "profile_language_id", nullable = false)
	public RefProfileLanguage getRefProfileLanguage() {
		return this.refProfileLanguage;
	}

	public void setRefProfileLanguage(RefProfileLanguage refProfileLanguage) {
		this.refProfileLanguage = refProfileLanguage;
	}

	@Column(name = "name", length = 254)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
