package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RefPrimaryLanguage generated by hbm2java
 */
@Entity
@Table(name = "ref_primary_language", schema = "public")
public class RefPrimaryLanguage implements java.io.Serializable {

	private int id;
	private String primaryLanguage;

	public RefPrimaryLanguage() {
	}

	public RefPrimaryLanguage(int id) {
		this.id = id;
	}

	public RefPrimaryLanguage(int id, String primaryLanguage) {
		this.id = id;
		this.primaryLanguage = primaryLanguage;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "primary_language", length = 15)
	public String getPrimaryLanguage() {
		return this.primaryLanguage;
	}

	public void setPrimaryLanguage(String primaryLanguage) {
		this.primaryLanguage = primaryLanguage;
	}

}
