package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * RefProfileLanguage generated by hbm2java
 */
@Entity
@Table(name = "ref_profile_language", schema = "public")
@JsonIdentityInfo(
		  generator = ObjectIdGenerators.PropertyGenerator.class, 
		  property = "id")
public class RefProfileLanguage implements java.io.Serializable {

	private int id;
	private String language;
	private Set<RefProfileLanguageTranslation> refProfileLanguageTranslations = new HashSet<RefProfileLanguageTranslation>(
			0);

	public RefProfileLanguage() {
	}

	public RefProfileLanguage(int id) {
		this.id = id;
	}

	public RefProfileLanguage(int id, String language,
			Set<RefProfileLanguageTranslation> refProfileLanguageTranslations) {
		this.id = id;
		this.language = language;
		this.refProfileLanguageTranslations = refProfileLanguageTranslations;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "language", length = 15)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refProfileLanguage")
	public Set<RefProfileLanguageTranslation> getRefProfileLanguageTranslations() {
		return this.refProfileLanguageTranslations;
	}

	public void setRefProfileLanguageTranslations(Set<RefProfileLanguageTranslation> refProfileLanguageTranslations) {
		this.refProfileLanguageTranslations = refProfileLanguageTranslations;
	}

}
