package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RefPeriodicEvent generated by hbm2java
 */
@Entity
@Table(name = "ref_periodic_event", schema = "public")
public class RefPeriodicEvent implements java.io.Serializable {

	private int id;
	private String name;
	private String description;
	private int periodicityValue;
	private int periodicityUnit;

	public RefPeriodicEvent() {
	}

	public RefPeriodicEvent(int id, String name, int periodicityValue, int periodicityUnit) {
		this.id = id;
		this.name = name;
		this.periodicityValue = periodicityValue;
		this.periodicityUnit = periodicityUnit;
	}

	public RefPeriodicEvent(int id, String name, String description, int periodicityValue, int periodicityUnit) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.periodicityValue = periodicityValue;
		this.periodicityUnit = periodicityUnit;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 254)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 254)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "periodicity_value", nullable = false)
	public int getPeriodicityValue() {
		return this.periodicityValue;
	}

	public void setPeriodicityValue(int periodicityValue) {
		this.periodicityValue = periodicityValue;
	}

	@Column(name = "periodicity_unit", nullable = false)
	public int getPeriodicityUnit() {
		return this.periodicityUnit;
	}

	public void setPeriodicityUnit(int periodicityUnit) {
		this.periodicityUnit = periodicityUnit;
	}

}
