package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * RefRole generated by hbm2java
 */
//@Entity
@Table(name = "ref_role", schema = "public")
public class RefRole implements java.io.Serializable {

	private int id;
	private String name;
	private boolean registrationAllowed;
	private Set<RegisteredUser> registeredUsers = new HashSet<RegisteredUser>(0);

	public RefRole() {
	}

	public RefRole(int id, String name, boolean registrationAllowed) {
		this.id = id;
		this.name = name;
		this.registrationAllowed = registrationAllowed;
	}

	public RefRole(int id, String name, boolean registrationAllowed, Set<RegisteredUser> registeredUsers) {
		this.id = id;
		this.name = name;
		this.registrationAllowed = registrationAllowed;
		this.registeredUsers = registeredUsers;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 254)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "registration_allowed", nullable = false)
	public boolean isRegistrationAllowed() {
		return this.registrationAllowed;
	}

	public void setRegistrationAllowed(boolean registrationAllowed) {
		this.registrationAllowed = registrationAllowed;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "user_role", schema = "public", joinColumns = {
			@JoinColumn(name = "role_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "user_id", nullable = false, updatable = false) })
	public Set<RegisteredUser> getRegisteredUsers() {
		return this.registeredUsers;
	}

	public void setRegisteredUsers(Set<RegisteredUser> registeredUsers) {
		this.registeredUsers = registeredUsers;
	}

}
