package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefSpectaclesType generated by hbm2java
 */
@Entity
@Table(name = "ref_spectacles_type", schema = "public")
public class RefSpectaclesType implements java.io.Serializable {

	private int id;
	private String spectaclesType;
	private Set<RefSpectaclesTypeTranslation> refSpectaclesTypeTranslations = new HashSet<RefSpectaclesTypeTranslation>(
			0);

	public RefSpectaclesType() {
	}

	public RefSpectaclesType(int id) {
		this.id = id;
	}

	public RefSpectaclesType(int id, String spectaclesType,
			Set<RefSpectaclesTypeTranslation> refSpectaclesTypeTranslations) {
		this.id = id;
		this.spectaclesType = spectaclesType;
		this.refSpectaclesTypeTranslations = refSpectaclesTypeTranslations;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "spectacles_type", length = 15)
	public String getSpectaclesType() {
		return this.spectaclesType;
	}

	public void setSpectaclesType(String spectaclesType) {
		this.spectaclesType = spectaclesType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refSpectaclesType")
	public Set<RefSpectaclesTypeTranslation> getRefSpectaclesTypeTranslations() {
		return this.refSpectaclesTypeTranslations;
	}

	public void setRefSpectaclesTypeTranslations(Set<RefSpectaclesTypeTranslation> refSpectaclesTypeTranslations) {
		this.refSpectaclesTypeTranslations = refSpectaclesTypeTranslations;
	}

}
