package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RefSkinType generated by hbm2java
 */
@Entity
@Table(name = "ref_skin_type", schema = "public")
public class RefSkinType implements java.io.Serializable {

	private int id;
	private String skinType;

	public RefSkinType() {
	}

	public RefSkinType(int id) {
		this.id = id;
	}

	public RefSkinType(int id, String skinType) {
		this.id = id;
		this.skinType = skinType;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "skin_type", length = 15)
	public String getSkinType() {
		return this.skinType;
	}

	public void setSkinType(String skinType) {
		this.skinType = skinType;
	}

}
