package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RefSpectaclesColor generated by hbm2java
 */
@Entity
@Table(name = "ref_spectacles_color", schema = "public")
public class RefSpectaclesColor implements java.io.Serializable {

	private int id;
	private String spectaclesColor;

	public RefSpectaclesColor() {
	}

	public RefSpectaclesColor(int id) {
		this.id = id;
	}

	public RefSpectaclesColor(int id, String spectaclesColor) {
		this.id = id;
		this.spectaclesColor = spectaclesColor;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "spectacles_color", length = 15)
	public String getSpectaclesColor() {
		return this.spectaclesColor;
	}

	public void setSpectaclesColor(String spectaclesColor) {
		this.spectaclesColor = spectaclesColor;
	}

}
