package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RefSpectaclesTypeTranslation generated by hbm2java
 */
@Entity
@Table(name = "ref_spectacles_type_translation", schema = "public")
public class RefSpectaclesTypeTranslation implements java.io.Serializable {

	private int id;
	private RefLanguage refLanguage;
	private RefSpectaclesType refSpectaclesType;
	private String name;

	public RefSpectaclesTypeTranslation() {
	}

	public RefSpectaclesTypeTranslation(int id, RefLanguage refLanguage, RefSpectaclesType refSpectaclesType) {
		this.id = id;
		this.refLanguage = refLanguage;
		this.refSpectaclesType = refSpectaclesType;
	}

	public RefSpectaclesTypeTranslation(int id, RefLanguage refLanguage, RefSpectaclesType refSpectaclesType,
			String name) {
		this.id = id;
		this.refLanguage = refLanguage;
		this.refSpectaclesType = refSpectaclesType;
		this.name = name;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language_id", columnDefinition="bpchar(3)", nullable = false)
	public RefLanguage getRefLanguage() {
		return this.refLanguage;
	}

	public void setRefLanguage(RefLanguage refLanguage) {
		this.refLanguage = refLanguage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "spectacles_type_id", nullable = false)
	public RefSpectaclesType getRefSpectaclesType() {
		return this.refSpectaclesType;
	}

	public void setRefSpectaclesType(RefSpectaclesType refSpectaclesType) {
		this.refSpectaclesType = refSpectaclesType;
	}

	@Column(name = "name", length = 254)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
