package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RefTopWearTranslation generated by hbm2java
 */
@Entity
@Table(name = "ref_top_wear_translation", schema = "public")
public class RefTopWearTranslation implements java.io.Serializable {

	private int id;
	private RefLanguage refLanguage;
	private RefTopWear refTopWear;
	private String name;

	public RefTopWearTranslation() {
	}

	public RefTopWearTranslation(int id, RefLanguage refLanguage, RefTopWear refTopWear) {
		this.id = id;
		this.refLanguage = refLanguage;
		this.refTopWear = refTopWear;
	}

	public RefTopWearTranslation(int id, RefLanguage refLanguage, RefTopWear refTopWear, String name) {
		this.id = id;
		this.refLanguage = refLanguage;
		this.refTopWear = refTopWear;
		this.name = name;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language_id", columnDefinition="bpchar(3)", nullable = false)
	public RefLanguage getRefLanguage() {
		return this.refLanguage;
	}

	public void setRefLanguage(RefLanguage refLanguage) {
		this.refLanguage = refLanguage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "top_wear_id", nullable = false)
	public RefTopWear getRefTopWear() {
		return this.refTopWear;
	}

	public void setRefTopWear(RefTopWear refTopWear) {
		this.refTopWear = refTopWear;
	}

	@Column(name = "name", length = 254)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
