package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefTopWear generated by hbm2java
 */
@Entity
@Table(name = "ref_top_wear", schema = "public")
public class RefTopWear implements java.io.Serializable {

	private int id;
	private String topWear;
	private Set<RefTopWearTranslation> refTopWearTranslations = new HashSet<RefTopWearTranslation>(0);

	public RefTopWear() {
	}

	public RefTopWear(int id) {
		this.id = id;
	}

	public RefTopWear(int id, String topWear, Set<RefTopWearTranslation> refTopWearTranslations) {
		this.id = id;
		this.topWear = topWear;
		this.refTopWearTranslations = refTopWearTranslations;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "top_wear", length = 15)
	public String getTopWear() {
		return this.topWear;
	}

	public void setTopWear(String topWear) {
		this.topWear = topWear;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refTopWear")
	public Set<RefTopWearTranslation> getRefTopWearTranslations() {
		return this.refTopWearTranslations;
	}

	public void setRefTopWearTranslations(Set<RefTopWearTranslation> refTopWearTranslations) {
		this.refTopWearTranslations = refTopWearTranslations;
	}

}
