package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RefTopWearColor generated by hbm2java
 */
@Entity
@Table(name = "ref_top_wear_color", schema = "public")
public class RefTopWearColor implements java.io.Serializable {

	private int id;
	private String topWearColor;

	public RefTopWearColor() {
	}

	public RefTopWearColor(int id) {
		this.id = id;
	}

	public RefTopWearColor(int id, String topWearColor) {
		this.id = id;
		this.topWearColor = topWearColor;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "top_wear_color", length = 15)
	public String getTopWearColor() {
		return this.topWearColor;
	}

	public void setTopWearColor(String topWearColor) {
		this.topWearColor = topWearColor;
	}

}
