package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefUserStatus generated by hbm2java
 */
//@Entity
@Table(name = "ref_user_status", schema = "public")
public class RefUserStatus implements java.io.Serializable {

	private int id;
	private String name;
	private Set<UserLoginDetails> userLoginDetailses = new HashSet<UserLoginDetails>(0);

	public RefUserStatus() {
	}

	public RefUserStatus(int id) {
		this.id = id;
	}

	public RefUserStatus(int id, String name, Set<UserLoginDetails> userLoginDetailses) {
		this.id = id;
		this.name = name;
		this.userLoginDetailses = userLoginDetailses;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 254)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refUserStatus")
	public Set<UserLoginDetails> getUserLoginDetailses() {
		return this.userLoginDetailses;
	}

	public void setUserLoginDetailses(Set<UserLoginDetails> userLoginDetailses) {
		this.userLoginDetailses = userLoginDetailses;
	}

}
