package com.temp.pack;
// Generated Jul 19, 2018 11:30:14 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SuccessStory generated by hbm2java
 */
@Entity
@Table(name = "success_story", schema = "public")
public class SuccessStory implements java.io.Serializable {

	private int id;
	private String successStory;
	private Date expiryDate;
	private Date creationDate;
	private Integer userId;
	private Integer childId;

	public SuccessStory() {
	}

	public SuccessStory(int id) {
		this.id = id;
	}

	public SuccessStory(int id, String successStory, Date expiryDate, Date creationDate, Integer userId,
			Integer childId) {
		this.id = id;
		this.successStory = successStory;
		this.expiryDate = expiryDate;
		this.creationDate = creationDate;
		this.userId = userId;
		this.childId = childId;
	}

	@Id

	@Column(name = "id", columnDefinition="bpchar(3)", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "success_story", length = 1000)
	public String getSuccessStory() {
		return this.successStory;
	}

	public void setSuccessStory(String successStory) {
		this.successStory = successStory;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expiry_date", length = 13)
	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "creation_date", length = 13)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "child_id")
	public Integer getChildId() {
		return this.childId;
	}

	public void setChildId(Integer childId) {
		this.childId = childId;
	}

}
